### ISSUE TITLE
create stack failure

### ISSUE THREAD

**Issue by jgroom33** [binxio/aws-cfn-update#2]
File does not appear to be shared

```
aws cloudformation wait stack-create-complete  --stack-name cfn-ami-provider 
Waiter StackCreateComplete failed: Waiter encountered a terminal failure state

Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 2542db0d-bf47-459d-9b22-5fa3fb7afbc9)
```

**Comment by mvanholsteijn** [comment]
Hi @jgroom33, can you tell me what you did to get this error?

**Comment by jgroom33** [comment]
I was attempting this:

https://github.com/binxio/cfn-ami-provider#demo

I noticed the example cf templates were in this repo tho.

**Comment by mvanholsteijn** [comment]
I fixed the README.md ; Which region are you in? I was unable to copy the lambda to eu-south-1 and af-south-1.

**Comment by jgroom33** [comment]
us-east-1

i assumed the error was because the zip file wasn't shared.  I'll try running again and ensure I can create the error again.
