### ISSUE TITLE
Tests fail with NoRegionError

### ISSUE THREAD

**Issue by iainelder** [binxio/aws-cfn-update#7]
This tool looks really promising for automating the manual steps required to import an existing resource into a a new stack.

I want to try it and maybe even add a new feature to better support this (a retain-resource command), but I can't get the unit tests to pass in my environment.

Am I missing some configuration?

I didn't see any instructions for testing in the README.

I start tox like because I have only Python3.8 installed:

```
tox -e py38
```

Error output below:

```
FAILED tests/test_latest_ami_updater.py::test_ami_update_inplace - botocore.exceptions.NoRegionError: You must specify a region.
FAILED tests/test_latest_ami_updater.py::test_with_other_filters - botocore.exceptions.NoRegionError: You must specify a region.
FAILED tests/test_latest_ami_updater.py::test_no_matching_ami_found - botocore.exceptions.NoRegionError: You must specify a region.
FAILED tests/test_latest_ami_updater.py::test_add_new_version - botocore.exceptions.NoRegionError: You must specify a region.
FAILED tests/test_latest_ami_updater.py::test_add_new_version_partitions - botocore.exceptions.NoRegionError: You must specify a region.
FAILED tests/test_latest_ami_updater.py::test_add_new_version_partitions_multiple_versions - botocore.exceptions.NoRegionError: You must specify a region.
FAILED tests/test_latest_ami_updater.py::test_add_new_versions_keep_old_refs - botocore.exceptions.NoRegionError: You must specify a region.
FAILED tests/test_packer_ami_updater.py::test_is_source_filter_name_match - botocore.exceptions.NoRegionError: You must specify a region.
FAILED tests/test_packer_ami_updater.py::test_create_describe_image_request - botocore.exceptions.NoRegionError: You must specify a region.
FAILED tests/test_packer_ami_updater.py::test_update - botocore.exceptions.NoRegionError: You must specify a region.
```

**Comment by mvanholsteijn** [comment]
Hi @iainelder , the AMI updater retrieves a list of AMIs from AWS, so it is not an official unit test. I have an AWS profile called `integration-test` which points to a test account and region for that purpose.

**Comment by iainelder** [comment]
With a profile like this in my CLI config file:

```cfg
[profile cfn-update-test]
sso_start_url = https://d-1111111111.awsapps.com/start
sso_region = eu-west-1
sso_account_id = 111111111111
sso_role_name = AdministratorAccess
region = eu-west-1
```

I can run tox like this:

```bash
export AWS_PROFILE=cfn-update-test
TOX_TESTENV_PASSENV=AWS_PROFILE tox --quiet -e py38
```

And the tests pass on my machine :-)

I think it's fine that some tests need to connect to an AWS account, but it wasn't clear how to set that up from the documentation.

The name of the profile doesn't seem to matter as long as it's set as the default profile from boto3's point of view.

How do you configure tox to use your integration-test profile?

**Comment by mvanholsteijn** [comment]
I do not use tox, but it looks like we need to stub the API call to make the tests independent of AWS.

**Comment by mvanholsteijn** [comment]
I will fix it for you.

**Comment by iainelder** [comment]
> I do not use tox

So how do you run the tests?

I used tox because the repo contains a tox.ini.

**Comment by mvanholsteijn** [comment]
Hi @iainelder, I stubbed the calls to describe_images, so you should be able to run the unit tests with any AWS connection.

**Comment by iainelder** [comment]
How do I run the unit tests?

**Comment by mvanholsteijn** [comment]
install the required stuff
```
$ pipenv shell
$ piping install -d
```

```
$ python setup.py test
```

or

```
$ py.test
```
